name: CustomViewDistance
main: me.drkmatr1984.customviewdistance.CustomViewDistance
version: 0.1
author: DrkMatr1984
description: A plugin for paperSpigot that adjusts the server ViewDistance dynamically based on a min and max value and current server TPS, allows users to set their own ViewDistance, and allows server owners to set ViewDistance by permission
